#ifndef JETSONGPIO_CONFIG_H
#define JETSONGPIO_CONFIG_H

#define JETSONGPIO_VERSION       "1.2.4"
#define JETSONGPIO_VERSION_MAJOR "1"
#define JETSONGPIO_VERSION_MINOR "2"
#define JETSONGPIO_VERSION_PATCH "4"

#endif
